app/src/main/java/com/github/se/studybuddies/ui/MainActivity.kt

I added the option to display oa message when the Google Sign In is successful or not.

Added confirmation message when the signIn is successuful

---

README.md

It's also to test the pull request system :)

Add figma link to README.md

---

app/src/main/java/com/github/se/studybuddies/ui/groups/GroupsHome.kt

Add a loading screen when waiting for the database to load the groups. This make the app more smooth.
This loading screen have been implemented so it can easily be used to other place later.

Loading screen

---

app/src/main/java/com/github/se/studybuddies/navigation/Destinations.kt
app/src/main/java/com/github/se/studybuddies/ui/solo_study/SoloStudyOption.kt

Just a quick PR to revert some strings that were extracted using a wrong function

Debugged a problem when extracting strings

---

.github/workflows/APK-build.yml

automatic APK generator

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/github/se/studybuddies/ui/map/MapScreen.kt
app/src/main/java/com/github/se/studybuddies/ui/permissions/Permissions.kt
app/src/main/java/com/github/se/studybuddies/ui/screens/SharedUI.kt
app/src/main/java/com/github/se/studybuddies/ui/todo/ToDoListScreen.kt

I corrected small issues remaining in the main. For example, there were some issues with the map which wasn't working properly on Android 14 (my tablet was an Android 13 so I didn't notice this earlier). Also we prevent the user from clicking again on a bottom navigation icon if he's already on the icon page (prevent from loading again the viewmodel and everything). Also I blocked the path to the EditToDo as this screen wasn't really working.

Small fixes

---

app/build.gradle.kts

Merge the build.gradle modif into M2

merge main into M2

---

app/src/main/java/com/github/se/studybuddies/ui/groups/GroupSetting.kt
app/src/main/java/com/github/se/studybuddies/viewModels/GroupViewModel.kt

just a small mistake from my part that made bugged group re-naming.
A real quick fix tho

Change group name

---

app/build.gradle.kts
app/src/androidTest/java/com/github/se/studybuddies/screens/CalendarScreen.kt
app/src/androidTest/java/com/github/se/studybuddies/tests/CalendarAppTest.kt
app/src/androidTest/java/com/github/se/studybuddies/tests/SharedTimerViewModelTest.kt
app/src/main/java/com/github/se/studybuddies/MainActivity.kt
app/src/main/java/com/github/se/studybuddies/calender/CalendarScreen.kt
app/src/main/java/com/github/se/studybuddies/calender/DateUtil.kt
app/src/main/java/com/github/se/studybuddies/data/CalendarDataSource.kt
app/src/main/java/com/github/se/studybuddies/data/CalendarUiState.kt
app/src/main/java/com/github/se/studybuddies/navigation/Route.kt
app/src/main/java/com/github/se/studybuddies/ui/account/LoginScreen.kt
app/src/main/java/com/github/se/studybuddies/ui/solo_study/SoloStudyOption.kt
app/src/main/java/com/github/se/studybuddies/viewModels/CalendarViewModel.kt
app/src/main/res/values/strings.xml

I implemented the calendar screen

Solo calendar 

---

app/src/androidTest/java/com/github/se/studybuddies/tests/MapTest.kt
app/src/main/java/com/github/se/studybuddies/MainActivity.kt
app/src/main/java/com/github/se/studybuddies/database/DatabaseConnection.kt
app/src/main/java/com/github/se/studybuddies/ui/map/MapScreen.kt
app/src/main/java/com/github/se/studybuddies/viewModels/UserViewModel.kt
app/src/main/res/values/strings.xml

During last friday demo, I realized that there was a bug with the map. It was related to the database and the way the location string was sent. I found that it was due the use of "R.string.offline". Thus I went back to my first idea of hardcoding  "offline" and it solved the issue

Map bug fix

---

app/src/main/java/com/github/se/studybuddies/MainActivity.kt
app/src/main/java/com/github/se/studybuddies/database/DatabaseConnection.kt
app/src/main/java/com/github/se/studybuddies/ui/groups/GroupScreen.kt
app/src/main/java/com/github/se/studybuddies/ui/groups/GroupSetting.kt
app/src/main/java/com/github/se/studybuddies/ui/groups/GroupsHome.kt

Add the hamburger menu to modifyGroup and to the screen when in a group
Correct small bug like "enter link" text zone being too big when no group existed
Small UI Improvement (smoother button and so on)
Add to userRemoveGroup when deleting an empty group deletion of chats and pictures
Add to deleteGroup the deletion of the chats
Reduce the complexity of the MainActivity

Group UI update

---

app/src/main/java/com/github/se/studybuddies/MainActivity.kt
app/src/main/java/com/github/se/studybuddies/ui/groups/GroupsHome.kt
app/src/main/java/com/github/se/studybuddies/ui/topics/TopicScreen.kt

Following the reviews from @cemuelle 
- Adding a new item expands its parent folder
- Indentation is based on hierarchy depth
- Field to input new item name is an AlertDialog

Topic improvement

---

app/build.gradle.kts
app/src/androidTest/java/com/github/se/studybuddies/screens/ChatScreen.kt
app/src/androidTest/java/com/github/se/studybuddies/screens/DirectMessageScreen.kt
app/src/androidTest/java/com/github/se/studybuddies/tests/CalendarAppTest.kt
app/src/androidTest/java/com/github/se/studybuddies/tests/ChatTest.kt
app/src/androidTest/java/com/github/se/studybuddies/tests/DirectMessageTest.kt
app/src/main/java/com/github/se/studybuddies/MainActivity.kt
app/src/main/java/com/github/se/studybuddies/data/CalendarDataSource.kt
app/src/main/java/com/github/se/studybuddies/data/DateUtil.kt
app/src/main/java/com/github/se/studybuddies/ui/calender/CalendarScreen.kt
app/src/main/java/com/github/se/studybuddies/ui/calender/DailyPlannerScreen.kt
app/src/main/java/com/github/se/studybuddies/ui/chat/ChatScreen.kt
app/src/main/java/com/github/se/studybuddies/ui/chat/DirectMessageScreen.kt
app/src/main/java/com/github/se/studybuddies/ui/shared_elements/SharedUI.kt

Modify chatScreen to reduce complexity and also add more test for chatScreen and DirectMessage

Reduce Complexity

---

app/src/main/AndroidManifest.xml

I know that it is a bad practise, however the maps doesn't work when generated with automatic APK

add_api_key

---

app/src/main/AndroidManifest.xml

Not optimal, but to make the APK work (working otherwise without)

Maps api key

---

app/src/main/java/com/github/se/studybuddies/data/Contact.kt
app/src/main/java/com/github/se/studybuddies/database/DatabaseConnection.kt
app/src/main/java/com/github/se/studybuddies/viewModels/ContactViewModel.kt

Solved a bug that allowed the creation of duplicate contacts

Contact list duplicates debug

---

app/build.gradle.kts
app/src/androidTest/java/com/github/se/studybuddies/screens/CreateToDoScreen.kt
app/src/androidTest/java/com/github/se/studybuddies/tests/CreateGroupTest.kt
app/src/androidTest/java/com/github/se/studybuddies/tests/CreateToDoTest.kt
app/src/main/java/com/github/se/studybuddies/data/todo/ToDo.kt
app/src/main/java/com/github/se/studybuddies/data/todo/ToDoStatus.kt
app/src/main/java/com/github/se/studybuddies/ui/todo/CreateToDo.kt
app/src/main/java/com/github/se/studybuddies/ui/todo/EditToDo.kt
app/src/main/java/com/github/se/studybuddies/ui/todo/HelperToDo.kt
app/src/main/java/com/github/se/studybuddies/ui/todo/ToDoListScreen.kt
app/src/main/java/com/github/se/studybuddies/viewModels/ToDoListViewModel.kt
app/src/main/res/values/strings.xml
build.gradle.kts

Added the base structure to implement tests to the todo list
Fixed a bug causing the due date of tasks to not get saved correctly
Updated the UI of the Edit and Create ToDo Screens
Updated the UI of the TodoList screen
Updated the tasks status and its usages to let the user modify it more conveniently
Other small improvements, fixes and code reformating

CreateToDo UI update

---

app/src/main/java/com/github/se/studybuddies/MainActivity.kt
app/src/main/java/com/github/se/studybuddies/ui/video_call/CallLobbyScreen.kt
app/src/main/java/com/github/se/studybuddies/ui/video_call/VideoCallScreen.kt

Debugged issues : 
- Video and microphone work fine in the call now
- Turning the screen won't cause crashes
Remaining issues : 
- Video and microphone not yet fully synchronized when first joining a call 
- Rotating the screen makes some buttons disappear, add scrolling ability in case of rotation 
- Leaving a call still doesn't actually leaves the call, there's a notification saying there's still a call in progress while supposed to have left it

Video call debugging : Part 1 

---

app/src/androidTest/java/com/github/se/studybuddies/utility/fakeDatabase/MockDatabase.kt
app/src/main/java/com/github/se/studybuddies/database/DatabaseConnection.kt
app/src/main/java/com/github/se/studybuddies/database/DbRepository.kt
app/src/main/java/com/github/se/studybuddies/ui/groups/GroupMembers.kt
app/src/main/java/com/github/se/studybuddies/ui/groups/GroupSetting.kt
app/src/main/java/com/github/se/studybuddies/ui/groups/GroupsHome.kt
app/src/main/java/com/github/se/studybuddies/viewModels/GroupViewModel.kt
app/src/main/res/values/strings.xml

In group, to add new members, add a list of all "friend" (for now all users). When clicking on one, it adds it to the group, or you can exit this page by clicking on the cross
Add a button to show this page on GroupSetting (Now there are two ways to add a member to a group)
Add the two buttons to add a member to GroupMember Page
Clean some code that called the DataBase for each member of a group and replace it by only one call
Correct a few bug and UI problem

Add group member from list

---

app/src/androidTest/java/com/github/se/studybuddies/utility/fakeDatabase/MockDatabase.kt
app/src/main/java/com/github/se/studybuddies/database/DatabaseConnection.kt
app/src/main/java/com/github/se/studybuddies/ui/topics/TopicCreation.kt
app/src/main/java/com/github/se/studybuddies/ui/topics/TopicScreen.kt
app/src/main/java/com/github/se/studybuddies/ui/topics/TopicSettings.kt

Previous PR on strong users had some formatting fail

euh idk some formatting failed

---

app/src/androidTest/java/com/github/se/studybuddies/tests/AccountSettingsTest.kt

signOut test removed, it was bugged and often failed many well-build PRs

Fix main not passing CI

---

app/src/main/java/com/github/se/studybuddies/ui/chat/ChatScreen.kt
app/src/main/java/com/github/se/studybuddies/ui/chat/DirectMessageScreen.kt
app/src/main/java/com/github/se/studybuddies/ui/chat/utility/ChatOption.kt
app/src/main/java/com/github/se/studybuddies/ui/chat/utility/SendTypeMessage.kt
app/src/main/java/com/github/se/studybuddies/ui/chat/utility/Utility.kt
app/src/main/java/com/github/se/studybuddies/viewModels/ChatViewModel.kt
app/src/main/java/com/github/se/studybuddies/viewModels/DirectMessageViewModel.kt
app/src/main/java/com/github/se/studybuddies/viewModels/MessageViewModel.kt

Add documentation in chat related parts

Chat Documentation
